README.md
package.json
src/templates/core/OpenAPI.hbs
src/templates/core/fetch/getHeaders.hbs
src/templates/core/fetch/request.hbs
src/templates/core/fetch/sendRequest.hbs
src/templates/core/functions/getToken.hbs
src/templates/core/node/getHeaders.hbs
src/templates/core/node/request.hbs
src/templates/core/node/sendRequest.hbs
src/templates/core/xhr/getHeaders.hbs
src/templates/core/xhr/request.hbs
src/templates/core/xhr/sendRequest.hbs
src/utils/registerHandlebarTemplates.ts
test/__snapshots__/index.spec.js.snap
test/e2e/scripts/browser.js
test/e2e/v2.babel.spec.js
test/e2e/v2.fetch.spec.js
test/e2e/v2.node.spec.js
test/e2e/v2.xhr.spec.js
test/e2e/v3.babel.spec.js
test/e2e/v3.fetch.spec.js
test/e2e/v3.node.spec.js
test/e2e/v3.xhr.spec.js

This PR closes #376. 
Sometimes, you need to run an asynchronous function to get your token from your auth provider. In order to always have the most up-to-date token, this function should be called at the time of request.
It seems like the tests pass for this, I'm testing it in my project now too. Will report back.

Allow asynchronous bearer token

---

README.md
src/index.spec.ts
src/openApi/v2/interfaces/Extensions/WithEnumExtension.d.ts
src/openApi/v2/interfaces/Extensions/WithNullableExtension.d.ts
src/openApi/v2/interfaces/OpenApiSchema.d.ts
src/openApi/v2/parser/getModelProperties.ts
src/openApi/v3/interfaces/Extensions/WithEnumExtension.d.ts
test/__snapshots__/index.spec.js.snap
test/spec/v2.json

This PR adds support for the `x-nullable` backport used in e.g. `drf-yasg` and [Apiary](https://help.apiary.io/api_101/swagger-extensions/#x-nullable).
#380

feat: Support x-nullable vendor extension

---

src/templates/exportService.hbs
src/templates/partials/parameters.hbs

This corrects issue #409 by adjusting the template slightly if useOptions is set. This already happens for the parameters partial, so it was relatively straightforward

Correctly document params when useOptions is set

---

src/client/interfaces/Model.d.ts
src/openApi/v3/parser/getModel.ts
src/templates/partials/schema.hbs
src/templates/partials/schemaComposition.hbs
src/templates/partials/type.hbs
src/templates/partials/typeIntersection.hbs
src/templates/partials/typeUnion.hbs
src/utils/registerHandlebarTemplates.ts
test/__snapshots__/index.spec.js.snap
test/spec/v3.json

The current composition schemas `allOf`, `oneOf`, and `anyOf`, only works on references. In this PR I've added support for types of arbitrary depth and type. This is done by promoting three composition types on the `Model.export` to preserve type information for the subsequent schema and model generation. 
I.e. the `Model` now have the type
```typescript
type Model = {
export: 
| 'reference' 
| 'generic' 
| 'enum' 
| 'array' 
| 'dictionary' 
| 'interface' 
| 'one-of' 
| 'any-of' 
| 'all-of'
type: ...
}
```
The following specification:
```json
{
"type": "object",
"properties": {
"any": {
"anyOf": [
{ "$ref": "#/components/schemas/A" },
{ "$ref": "#/components/schemas/B" },
{ "$ref": "#/components/schemas/C" },
]
},
"one": {
"oneOf": [
{ "$ref": "#/components/schemas/A" },
{ "$ref": …
```

feat: Improve support for allOf, oneOf, and anyOf

---

src/openApi/v2/parser/escapeDescription.spec.ts
src/openApi/v2/parser/escapeDescription.ts
src/openApi/v2/parser/getOperationErrors.ts
src/openApi/v3/parser/escapeDescription.spec.ts
src/openApi/v3/parser/escapeDescription.ts
src/openApi/v3/parser/getOperationErrors.ts

closes #451 
Backtick symbol in service description is not being escaped correctly. As result -> invalid TS is generated.
```
public static async getUser(
userId: number,
): Promise<User> {
const result = await __request({
method: 'GET',
path: `/users/${userId}`,
errors: {
404: `|Error code         |Description                                                  |
* |-------------------|-------------------------------------------------------------|
* |RESOURCE_NOT_FOUND |The user specified in the `userId` path parameter: <br>- either does not exist;<br>- or ....`,
},
});
return result.body;
}
```
**\`userId\`**   should be   **\\\`userId\\\`**

Backquote/backtick symbol (`) is not escaped correctly

---

src/templates/partials/parameters.hbs

This PR omits generation of comments to parameters if `useOptions` is true and the parameter doesn't have description field.
After upgrade from 0.5.4 to 0.7.0 our re-generated types have a lot of empty comments in them, because parameters don't have the description field filled in.
This change has been introduced in https://github.com/ferdikoomen/openapi-typescript-codegen/pull/410

Fix empty parameter descriptions

---

package.json
src/utils/getOpenApiSpec.ts
yarn.lock

This is a replacement for #433 , using a library to parse external and remote $ref instances so that an openapi.yml can be split up at development time, but reassembled for the purposes of generating types.

Allow importing external references

---

src/openApi/v2/parser/getEnum.ts
src/openApi/v3/parser/getEnum.ts
test/__snapshots__/index.spec.js.snap
test/spec/v2.json
test/spec/v3.json

Negative numbers in generated enums are broken.
Here's the playground how it's not working and how PR fixes it.
https://www.typescriptlang.org/play?#code/KYOwrgtgBAouEHUCWAXAFgOUgI2AJygG8BYAKCigH0BGKAXimoBoyLKAmeqdl0gXzJlQkWPGTosEXHgBCeAPYBrUEVZUAtLQabebLY11VODHmQGkh8UZHGYc+AGJIAHsAAmq8lABElTd64dNV9qAIZmYI4w7l5zMjgbVDspfAA6GnixJMlpdPZBUgTEbPs8J1c3dOpMxIlS8vc8muK6lLKXdwBtX38AXSA

Wrap negative numbers in quotes, fix Enums in TypeScript

---

src/client/interfaces/OperationParameter.d.ts
src/openApi/v2/parser/getOperationParameter.ts
src/openApi/v3/parser/getMediaType.ts
src/openApi/v3/parser/getOperationParameter.ts
src/openApi/v3/parser/getOperationRequestBody.ts
src/templates/core/ApiRequestOptions.hbs
src/templates/core/fetch/getHeaders.hbs
src/templates/core/fetch/getRequestBody.hbs
src/templates/core/node/getHeaders.hbs
src/templates/core/node/getRequestBody.hbs
src/templates/core/xhr/getHeaders.hbs
src/templates/core/xhr/getRequestBody.hbs
src/templates/exportService.hbs
test/__snapshots__/index.spec.js.snap

The current version of the `openapi-typescript-codegen` does not always respect the [Media Type](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#mediaTypeObject) of the requestBody in the `Content-Type` Request header.
Example:
If we have an operation with the following `requestBody` property ...
```json
{
"requestBody": {
"content": {
"application/json": {
"schema": {
"type": "string"
}
}
}
}
}
```
... and we use the following method in our generated client ...
```js
await api.operationMethod({ requestBody: "test" });
```
... the client will send a request with the `Content-Type` header `text/plain` because of the following code:
1. https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/src/templates/core/fetch/getHeaders.hbs#L25-L26
1. …

Fix: Respect mediatype

---

src/openApi/v2/parser/getOperationParameterName.ts
src/openApi/v3/parser/getOperationParameterName.ts
src/templates/core/fetch/getHeaders.hbs
src/templates/core/node/getHeaders.hbs
src/templates/core/xhr/getHeaders.hbs
test/__snapshots__/index.spec.js.snap

PR for issue https://github.com/ferdikoomen/openapi-typescript-codegen/issues/760
- Reduce headers by checking value of typeof undefined
- Update snapshot test
- run yarn eslint:fix (getOperationParamaterName changes)
With thanks to @vanhoofmaarten

Filter undefined headers before creating the headers

---

src/templates/core/functions/base64.hbs

Hi there, a very small pull request that would help me a lot
The base64 function tries using the btoa function and falls back to
using Buffer if btoa is not available.
In the context of a dom, you have btoa, and you may not necessarily have
Buffer, and in the case the fallback branch creates a compilation error
"TS2591: Cannot find name 'Buffer'."
Add a @ts-ignore in the fallback branch because we will always have
either btoa or Buffer available in the forseable future.

Fix client compilation error in base64()

---

rollup.config.js
src/templates/partials/schemaComposition.hbs
src/templates/partials/schemaGeneric.hbs
src/templates/partials/schemaInterface.hbs
src/utils/registerHandlebarHelpers.ts
test/__snapshots__/index.spec.js.snap

As mentioned in the README, the [Export Schemas](https://github.com/ferdikoomen/openapi-typescript-codegen#runtime-schemas---exportschemas) option is really helpful when creating forms driven by OpenAPI spec. 
However, I feel that it would be even more helpful when the description is available in the schema output as well, so it can be used as a label.

Add description to schema output

---

src/templates/core/fetch/getHeaders.hbs
src/templates/core/fetch/getRequestBody.hbs
src/templates/core/fetch/request.hbs
src/templates/core/functions/isFormData.hbs
src/templates/core/node/getHeaders.hbs
src/templates/core/node/getRequestBody.hbs
src/templates/core/xhr/getHeaders.hbs
src/templates/core/xhr/getRequestBody.hbs
src/utils/registerHandlebarTemplates.ts
test/__snapshots__/index.spec.js.snap

This PR adds support for sending a `FormData` directly as `requestBody`. Often used for file upload.
Note the warning here:  https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects that you should  not explicitly set the `Content-Type` header on the request.

Allow FormData as body argument

---

src/openApi/v2/parser/getOperationParameterName.ts
src/openApi/v3/parser/getModel.ts
src/openApi/v3/parser/getModelProperties.ts
src/openApi/v3/parser/getOperationParameterName.ts
src/templates/partials/schemaGeneric.hbs
src/utils/discriminator.ts
test/__snapshots__/index.spec.js.snap
test/spec/v3.json

Continuation of #645 but in a cleaned branch...
Currently it seems there is no support for discriminators from the V3 spec  in the generator.
This PR adds some preliminary support so that instead of:
```
export type ModelCircle = {
kind: string;
radius?: number;
}
export type ModelSquare = {
kind: string;
sideLength?: number;
}
export type Shape = Circle | Square;
```
It generates (not the the `kind: string` is replaced)
```
export type ModelCircle = {
kind: 'circle';
radius?: number;
}
export type ModelSquare = {
kind: 'square';
sideLength?: number;
}
export type Shape = Circle | Square;
```
Added some tests as well, let me know what you think!

Adding oneOf with discriminator property support

---

types/index.d.ts

https://github.com/ferdikoomen/openapi-typescript-codegen/issues/934
the following field is currently available in cli interface as:
`    --postfix <value>         Service name postfix (default: "Service")`
and in project src at https://github.com/ferdikoomen/openapi-typescript-codegen/blob/00cb70bdda17c7be2322551f5fd9b028438b49d0/src/index.ts#L23
but isn't available in typedefs.
Thanks!

Fix: Add missing postfix field to options typedef

---

src/openApi/v3/parser/getServices.spec.ts
src/openApi/v3/parser/getServices.ts

Before this change, if your OpenAPI spec had an empty `tags` property, the service file would not be created.
After this change, the behaviour in this scenario is the same as if there was no tags property at all.
One thing to note (and I'm happy to revert it if you don't think its better), is that I've changed the default tag from "Service" to "Unnamed". The thinking behind this is that `UnnamedService` is a better name to use than `ServiceService`.

Handle empty tags

---

src/openApi/v3/parser/getModelComposition.ts
test/__snapshots__/index.spec.ts.snap
test/spec/v3.json

Fixes #964.
In case of "simple" dictionary (`Record<string, number>` or `Record<string,array<number>>`, model.type was set to `number` in `parser/getModel.ts` function. But in case of composite, `type` was  not explicitly set and defaulted to `any`.
I didn't want to change this type in the `getModel` function, as it might have some other implications, so I just added another check in when to ignore a model within composition.
Added 3 more test objects to the suite, so it covers all three cases.

Fixes a bug that prevented using complex dictionaries within compositions

---

src/templates/core/BaseHttpRequest.hbs

Makes `BaseHttpRequest` abstract:
* it's (at least to my understanding) obviously not meant for direct instantiation
* the current version will trigger a TS compile error `TS6133` when option `noUnusedParameters: true` is set for the unused `options` argument
* (alternatively, this could be fixed by renaming it to `_options`)

Make BaseHttpRequest abstract

---

src/templates/core/axios/request.hbs

Hey there! I encountered TypeScript error while using your amazing project: type checker complains about imported types in clients generated for `axios` backend.
In this PR I changed the template for request file relevant to `axios`: now `AxiosRequestConfig` and `AxiosResponse` symbols are being imported as types.
Type-only imports: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

Use type-only imports for `axios`

---

src/templates/core/fetch/getRequestBody.hbs

The same can be done for other client types.

Fix undefined request body when body is a valid JSON falsy value: false or 0, "".

---

src/templates/core/fetch/getResponseBody.hbs
src/templates/core/node/getResponseBody.hbs
src/templates/core/xhr/getResponseBody.hbs
test/__snapshots__/index.spec.ts.snap

I have several projects that return a `application/problem+json` content type. As seen in [this RFC](https://datatracker.ietf.org/doc/html/rfc7807), it should always be possible to parse it with `response.json()`.
The [symfony](https://symfony.com/) framework uses this as default, so when my back-end is build with symfony I cannot select items in the body of the error at this moment since it is parsed as text.
This PR adds support for the `application/problem+json` content type so that the errors in json format are parsed as json instead of text.

Add json support for application/problem+json content type

---

src/openApi/v3/parser/getModel.ts
test/__snapshots__/index.spec.ts.snap
test/spec/v3.json

> A free-form object (arbitrary property/value pairs) is defined as:
>
>     type: object
>
> This is equivalent to
>
>     type: object
>     additionalProperties: true
>
> and
>
>     type: object
>     additionalProperties: {}
https://swagger.io/docs/specification/data-models/data-types/

Support free-form objects

---

src/templates/core/functions/catchErrorCodes.hbs

'Generic Error' gives no insight into the nature of the issue, whereas having at least the http status conveys a great deal for troubleshooting

add more detail to Generic Error message for easier troubleshooting

---

src/templates/core/OpenAPI.hbs

A key being optional is different than the value being optional. Former indicates missing keys, while latter indicate, required key but missing value.
When defining a type like this, we're explicitly stating that the key must exists, but its value could be undefined. 
```ts
export type OpenAPIConfig = {
myKey: string | undefined;
};
```
**`Valid`**
`const invalid: OpenAPIConfig = {myKey: undefined}`
*`Invalid`*
`const invalid: OpenAPIConfig = {}`
Which is different from following that says, key could be missing - which translates into the value being missing as well. Which is why with `exactOptionalPropertyTypes` all optional keys need to explicitly state `undefined` as value type. 
```ts
export type OpenAPIConfig = {
myKey?: string | undefined;
};
```
**`Valid`**
`const invalid: …

Support exactOptionalPropertyTypes

---

docs/axios-support.md
src/templates/core/axios/request.hbs
src/templates/core/axios/sendRequest.hbs

This PR solves #942, and any issues requesting specific advanced axios features (e.g. #1428, part of #1084)
Currently, it is impossible to add any interceptors to axios without modifying the global axios instance, which can effect other parts of your program in unwanted ways.
Also, hiding away the actual usage of the axios library in the `request` file means this generator will always play catch up with new axios features, or people asking for very specific axios parameters to be externalized.
This PR allows passing in a custom axios instance to the inner request module, providing an escape hatch for advanced users.

Allow usage of a custom axios instance

---

package.json

In NPM, the `prepublishOnly` script is run only before running `npm publish`. However, this means that people trying to use the git version of of this project (i.e. with `npm install github:ferdikoomen/openapi-typescript-codegen`) won't get a working version of this project, since there will be nothing in the `dist/` folder.
[NPM (since v4.0.0)][1] supports a `prepack` script, that is called:
> * Runs BEFORE the package is packed
> * Runs BEFORE the package is published
> * Runs on local `npm install` without any arguments
> * Run AFTER `prepublish`, but BEFORE `prepublishOnly`
> * NOTE: If a package being installed through git contains a `prepare`
>   script, its `dependencies` and `devDependencies` will be installed,
>   and the prepare script will be run, before the package is packaged …

build: use npm prepare instead of prepublishOnly

---

src/templates/partials/header.hbs

Thanks for this great code generator.
I wonder if you would consider this addition, it adds a line to the file header indicating that the file is auto-generated. Feedback I got from my collaborators is that it was not obvious that files created by openapi-typescript-codegen were automatically generated.

Indicate auto-generation in file headers.

---

package-lock.json
src/templates/core/CancelablePromise.hbs
test/__snapshots__/index.spec.ts.snap

Adressing issue #1626.
Proposal for a slight adjustment of the resolving process for the `CancelablePromise`.
As said, I have no clue why this issue occurs when updating Next.js for me, but something in the background must've changed that I'm not aware of. The exact same generated code works for me with Next.js 12.
It seems to try to call the `resolve()` function before the instance is initiated and not resolving the valid syntax of `this.#resolve?.(value)` correctly.
Doing the `undefined` check without an intermediate value, seems to resolve this issue for me, so I would propose this in a PR and would be interested in your opinions on this.
Imo, this shouldn't affect other users in a negative way and only increase the code size very slightly.
So instead of `this.#resolve?.(value);`, I …

fix: adjust promise resolve for next issue

---

src/templates/core/axios/sendRequest.hbs

Fix for #2063 
added backwards compatibility for axios vulnerable parameter
I checked all the changes for axios, and it looks like setting it to true when credentials are forced for any domain is the right choice. 
I'm not able to run the tests properly as #2052 causes wrong paths to be resolved.
I will take a look at that PR and see if it helps.

fix: updated axios sendRequest (#2063)

---

src/templates/core/angular/getHeaders.hbs
src/templates/core/axios/getHeaders.hbs
src/templates/core/fetch/getHeaders.hbs
src/templates/core/node/getHeaders.hbs
src/templates/core/xhr/getHeaders.hbs

This fixes a bug, where the `Content-Type` header would be reset to the default, when the `request.body` contains a falsy value. 
For example, given using the fetch api, when sending a request with body `0` (i.e. the number zero), the `Content-Type` header would default to `text/plain; utf-8` (which is the browser default), even when `application/json` would be expected (and would be set if the request body was e.g. `1`, i.e. the number one).

fix: infer media-type for falsy bodies except 'undefined'

---

src/templates/partials/header.hbs

I think this was intended to say `do not edit`

fix: typo in template header
